version: '3.8'

services:
    server:
        build: .
        network_mode: host
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - HOST_IP=${HOST_IP:-localhost}

    frontend:
        build: ./scraper
        network_mode: host
        volumes:
            - ./scraper:/app
            - /app/node_modules
        depends_on:
            - server
